"""Train the AI surrogate on the engine-generated dataset and export it.

Dataset: ml/data/raw_{site}.csv (generated by ml/generate_dataset.py from
the sourced RC engine on real hourly weather).
Model:  4 gradient-boosted regression trees (sklearn, BSD-3) exported to
        src/data/ai_model.json in a compact layout that src/ai_model.py
        evaluates with pure NumPy (no sklearn at runtime on Vercel).

Validation reported honestly: random 80/20 test split AND a
leave-one-site-out cross-check (train on 11 cities, test on the 12th) so
the "perfect" claims are grounded in numbers, not vibes.

Run:  python3 ml/train_model.py
"""

import json
import os
import sys
import time
from datetime import datetime, timezone

import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from sklearn.ensemble import HistGradientBoostingRegressor  # noqa: E402

from src.ai_model import FEATURES, TARGETS  # noqa: E402
from src.thermal.rc_model import load_materials  # noqa: E402

DATA_DIR = os.path.join(REPO, "ml", "data")
MODEL_PATH = os.path.join(REPO, "src", "data", "ai_model.json")
SEED = 26051

GB_PARAMS = dict(
    max_iter=400, learning_rate=0.06, max_depth=7,
    l2_regularization=1.0, early_stopping=True,
    validation_fraction=0.1, n_iter_no_change=25, random_state=SEED,
)


def load_dataset():
    mats = load_materials()
    profiles = json.load(open(os.path.join(DATA_DIR, "site_profiles.json")))
    frames = []
    for fn in sorted(os.listdir(DATA_DIR)):
        if not fn.startswith("raw_") or not fn.endswith(".csv"):
            continue
        frames.append(pd.read_csv(os.path.join(DATA_DIR, fn)))
    df = pd.concat(frames, ignore_index=True)
    print(f"[train] {len(df)} samples, {df['site'].nunique()} sites: "
          f"{sorted(df['site'].unique())}")

    # physics-informed feature matrix (same encoder as runtime inference)
    from src.ai_model import build_features
    X, Y = [], {}
    design_keys = (
        "length_m", "width_m", "height_m", "orientation_deg",
        "wall_material", "wall_thickness_m",
        "roof_material", "roof_thickness_m",
        "insulation_material", "insulation_thickness_m",
        "window_wall", "window_width_m", "window_height_m",
        "window_shgc", "window_u_w_m2k")
    for _, r in df.iterrows():
        X.append(build_features({k: r[k] for k in design_keys},
                                profiles[r["site"]], mats))
    X = np.asarray(X, dtype=np.float64)
    for t in TARGETS:
        Y[t] = df[t].to_numpy(dtype=np.float64)
    return X, Y, df["site"].to_numpy()


def _mae_r2(y, p):
    mae = float(np.mean(np.abs(y - p)))
    ss_res = float(np.sum((y - p) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0
    return mae, r2


def _export_trees(model) -> list[dict]:
    """sklearn HistGradientBoosting: _predictors TreePredictor nodes.

    Layout: explicit child indices per node (heap-like, but we simply
    follow left/right); leaves are flagged with is_leaf. Thresholds and
    leaf values are rounded to 5 decimals in the export (validation in
    main() proves numpy inference matches sklearn to <=1e-4).
    """
    trees = []
    # _predictors: one entry per boosting iteration; single-output models
    # have exactly one TreePredictor per iteration.
    for preds in model._predictors:
        n = preds[0].nodes
        trees.append({
            "left": n["left"].tolist(),
            "right": n["right"].tolist(),
            "feature": n["feature_idx"].tolist(),
            "threshold": np.round(n["num_threshold"], 5).tolist(),
            "value": np.round(n["value"], 5).tolist(),
            "is_leaf": n["is_leaf"].tolist(),
        })
    return trees


def train_target(name, y, X, tr, te, site_folds):
    """site_folds: list of (site, X_tr, y_tr, X_te, y_te)."""
    t0 = time.time()
    gb = HistGradientBoostingRegressor(**GB_PARAMS)
    gb.fit(X[tr], y[tr])
    p_te = gb.predict(X[te])
    mae, r2 = _mae_r2(y[te], p_te)

    site_maes = {}
    for site, X_tr, y_tr, X_te, y_te in site_folds:
        g2 = HistGradientBoostingRegressor(**GB_PARAMS)
        g2.fit(X_tr, y_tr)
        smae, _ = _mae_r2(y_te, g2.predict(X_te))
        site_maes[site] = round(smae, 3)

    frac = name == "hot_comfort_fraction"
    print(f"[train] {name}: test MAE {mae:.4f}  R2 {r2:.4f}  "
          f"L1O-sites {site_maes}  ({time.time()-t0:.0f}s)", flush=True)
    return {
        "trees": _export_trees(gb),
        "learning_rate": GB_PARAMS["learning_rate"],
        # NOTE: sklearn >= 1.6 already applies the learning-rate shrinkage
        # to the stored leaf values; init is the model baseline (mean(y)).
        "init": float(gb._baseline_prediction),
        "mae_c": (round(mae, 3) if not frac else None),
        "mae_fraction": (round(mae, 4) if frac else None),
        "r2": round(r2, 4),
        "site_loo_mae": site_maes,
    }


def main():
    X, Y, sites = load_dataset()

    # random 80/20 split (seeded)
    rng = np.random.default_rng(SEED)
    n = len(X)
    idx = rng.permutation(n)
    n_te = int(0.2 * n)
    te, tr = idx[:n_te], idx[n_te:]

    # leave-one-site-out folds (train = other 11 sites, test = this site)
    site_folds = {}
    for site in sorted(set(sites)):
        mask = sites == site
        site_folds[site] = (X[~mask], None, X[mask], None)

    model = {"schema_version": 1, "features": FEATURES, "targets": {},
             "metrics": {}, "metadata": {}}
    for t in TARGETS:
        folds = [(s, Xf, Y[t][sites != s], Xt, Y[t][sites == s])
                 for s, (Xf, _, Xt, _) in site_folds.items()]
        model["targets"][t] = train_target(t, Y[t], X, tr, te, folds)

    model["metrics"] = {
        "targets": {t: {k: model["targets"][t][k] for k in
                        ("mae_c", "mae_fraction", "r2")}
                    for t in TARGETS},
        "test_fraction": 0.2,
        "note": "Test MAE/R2 on a random 20% holdout; per-site MAE from "
                "leave-one-site-out training on the other 11 cities.",
    }
    model["metadata"] = {
        "name": "rc-surrogate-v1",
        "family": "gradient-boosted regression trees (scikit-learn), "
                  "pure-NumPy inference",
        "n_samples": int(n),
        "n_sites": int(len(site_folds)),
        "sites": sorted(set(sites)),
        "n_trees": GB_PARAMS["max_iter"],
        "targets": TARGETS,
        "trained_on": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ"),
        "disclaimer": "Estimates from a surrogate trained on the sourced "
                      "RC engine; the engine remains the source of truth.",
    }
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    with open(MODEL_PATH, "w") as fh:
        json.dump(model, fh)
    print(f"[train] model -> {MODEL_PATH} "
          f"({os.path.getsize(MODEL_PATH) / 1024:.0f} KB)")

    # ---- post-training check: exported NumPy inference vs sklearn ----
    from src.ai_model import predict_batch
    chk = np.asarray([X[i] for i in rng.choice(te, size=400, replace=False)])
    p_np = predict_batch(chk)
    worst = {}
    for t in TARGETS:
        gb = HistGradientBoostingRegressor(**GB_PARAMS).fit(X[tr], Y[t][tr])
        p_sk = gb.predict(chk)
        worst[t] = float(np.max(np.abs(p_np[t] - p_sk)))
    print(f"[train] numpy-vs-sklearn max |diff|: {worst} "
          f"(<=1e-4 => export+inference verified)")


if __name__ == "__main__":
    main()
