-- Seed data for SIH26051 Shelter — generated from materials.csv and
-- config/config.yaml (python: regenerate with scripts/sync_supabase.py)
-- Run in the Supabase SQL editor, or:  supabase db push

-- Materials (sourced in data/external/materials.csv)
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('brick', 'masonry', 0.72, 1920, 840, 0.7, 0.9, 0.2, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (common brick, ~119 lb/ft3); absorptance/emissivity: ASHRAE 2021 Ch.26 Table 24 (red brick, aged)', 'default wall material') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('concrete', 'masonry', 1.7, 2300, 880, 0.65, 0.91, 0.12, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (dense concrete ~144 lb/ft3); emissivity: ASHRAE Ch.26 (concrete 0.85-0.95)', 'used for floor + rcc_slab roof') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('rcc_slab', 'masonry', 1.7, 2300, 880, 0.65, 0.91, 0.12, 'same dense-concrete row; reinforced concrete approx. as dense concrete (ASHRAE HOF 2021 Ch.26)', 'roof alias for concrete') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('stone', 'masonry', 2.8, 2650, 790, 0.6, 0.9, 0.15, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (granite k ~2.7-3.5 W/mK, 165 lb/ft3)', 'local stone alternative') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('rammed_earth', 'masonry', 0.75, 1800, 1000, 0.6, 0.9, 0.3, 'Rammed earth: k 0.6-1.0 W/mK, rho ~1700-2000 kg/m3 (e.g. Hall & Allinson 2009; CIBSE Guide A); absorptance: earth 0.6', 'verify with local soil test for final submission') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('timber', 'wood', 0.14, 640, 1630, 0.6, 0.9, 0.05, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (yellow pine); cp ~1.63 kJ/kgK', 'lightweight frame option') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('plywood', 'wood', 0.12, 550, 1210, 0.6, 0.9, 0.02, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (plywood); cp ~1.21 kJ/kgK', 'sheathing layer') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('mineral_wool', 'insulation', 0.036, 70, 840, 0.3, 0.9, 0.05, 'ISO 10456 / EN 13162 typical: k 0.035-0.045 W/mK, rho 25-200 kg/m3; absorptance typical for insulation behind cladding', 'rockwool batt') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('eps', 'insulation', 0.036, 25, 1450, 0.3, 0.9, 0.05, 'ISO 10456 / EN 13163 typical: EPS k 0.030-0.040 W/mK, rho 15-30 kg/m3; cp ~1.2-1.5 kJ/kgK (manufacturer datasheets)', 'expanded polystyrene board') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('xps', 'insulation', 0.033, 32, 1450, 0.3, 0.9, 0.05, 'ISO 10456 / EN 13164 typical: XPS k 0.029-0.036 W/mK; cp ~1.4-1.5 kJ/kgK', 'extruded polystyrene board') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('puf_sandwich_panel', 'panel', 0.023, 40, 1400, 0.5, 0.9, 0.05, 'PUR/PIR panel cores k 0.022-0.028 W/mK (EN 14509, manufacturer datasheets); outer steel skin absorptance 0.5 typical (galvanised, painted)', 'prefab shelter option') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;
insert into public.materials (material, category, k_W_mK, density_kg_m3, cp_J_kgK, solar_absorptance, emissivity, thickness_m, source, notes) values ('gi_sheet', 'metal', 50.0, 7850, 480, 0.55, 0.28, 0.0006, 'ASHRAE Handbook-Fundamentals 2021 Ch.26 (steel k ~45-50 W/mK, 490 lb/ft3, cp 0.12 Btu/lbF = 502 J/kgK); galvanised steel solar absorptance 0.5-0.65, emissivity 0.28 (ASHRAE Ch.26 Table 24)', 'corrugated sheet roof/walls') on conflict (material) do update set k_W_mK = excluded.k_W_mK, source = excluded.source;

-- Default location (edit or add more via the app)
insert into public.locations (location_id, name, latitude, longitude, elevation_m, timezone) values ('prayagraj', 'Prayagraj', 25.4358, 81.8463, 98, 'Asia/Kolkata') on conflict (location_id) do nothing;
