"""Build an EnergyPlus IDF for the SIH26051 shelter (shoebox model).

The IDF is generated from the same config + materials.csv used by the fast
RC model, so the two models describe the SAME shelter. The floor is modelled
as exposed-to-outdoors (elevated/stilt shelter); for a slab-on-grade model,
change the floor surface boundary condition and add a ground-temperature
object (see docs/model_notes.md).
"""
from pathlib import Path

import numpy as np

from src.geometry.shelter import Shelter
from src.thermal.rc_model import load_materials


def _rotate_xy(x, y, deg):
    """Rotate (x, y) by deg degrees clockwise (viewed from above)."""
    th = np.radians(deg)
    c, s = np.cos(th), np.sin(th)
    return (c * x + s * y, -s * x + c * y)


def _box_vertices(cfg):
    """Return surface vertex lists for the un-rotated box, then rotate.

    Convention: with orientation 0 the front wall faces south (-Y).
    Every vertical wall is ordered  top-left -> bottom-left -> bottom-right
    -> top-right  (in the wall's own plane), which satisfies
    (p2->p3 horizontal) x (p2->p1 vertical) = outward normal, i.e. the
    CounterClockwise-as-seen-from-outside rule of GlobalGeometryRules.
    Returns dict wall -> list of (x, y, z).
    """
    sh = cfg["shelter"]
    lx, wy, hz = sh["length_m"], sh["width_m"], sh["height_m"]
    deg = sh["orientation_deg"]
    walls = {
        # p1=top-left, p2=bottom-left, p3=bottom-right, p4=top-right
        "south": [(0, 0, hz), (0, 0, 0), (lx, 0, 0), (lx, 0, hz)],        # normal -Y
        "north": [(lx, wy, hz), (lx, wy, 0), (0, wy, 0), (0, wy, hz)],    # normal +Y
        "west": [(0, wy, hz), (0, wy, 0), (0, 0, 0), (0, 0, hz)],         # normal -X
        "east": [(lx, 0, hz), (lx, 0, 0), (lx, wy, 0), (lx, wy, hz)],     # normal +X
        "roof": [(0, 0, hz), (lx, 0, hz), (lx, wy, hz), (0, wy, hz)],     # normal +Z
        "floor": [(0, 0, 0), (0, wy, 0), (lx, wy, 0), (lx, 0, 0)],        # normal -Z
    }
    out = {}
    for name, verts in walls.items():
        out[name] = [(*_rotate_xy(x, y, deg), z) for (x, y, z) in verts]
    return out


def _window_vertices(wall_verts, u0_frac, u1_frac, z_sill, z_top):
    """Inset opening vertices on a wall.

    wall_verts order: p1 (top-left), p2 (bottom-left), p3 (bottom-right),
    p4 (top-right) in the wall's local frame; u runs p2->p3, w runs p2->p1.
    Returns the 4 window vertices in the same cyclic order (same normal).
    """
    p1, p2, p3, p4 = wall_verts
    u_vec = np.array(p3) - np.array(p2)
    w_vec = np.array(p1) - np.array(p2)
    # in-plane coordinates of the four wall corners
    def point(u_frac, w_val):
        return tuple(np.array(p2) + u_vec * u_frac + w_vec * w_val)
    corners = [point(u0_frac, z_top), point(u0_frac, z_sill),
               point(u1_frac, z_sill), point(u1_frac, z_top)]
    return corners


def _fmt_verts(verts) -> str:
    return ", ".join(f"{x:.3f},{y:.3f},{z:.3f}" for (x, y, z) in verts)


def build_idf(cfg: dict, materials, out_path: str | Path) -> Path:
    """Generate the full IDF text and write it to out_path."""
    loc, sh, sim = cfg["location"], cfg["shelter"], cfg["simulation"]
    eplus = cfg.get("energyplus", {})
    year = int(cfg["climate"]["data_year"])
    steps = int(eplus.get("timesteps_per_hour", 4))

    shelter = Shelter(
        length_m=sh["length_m"], width_m=sh["width_m"], height_m=sh["height_m"],
        orientation_deg=sh["orientation_deg"],
        wall_material=sh["wall_material"], wall_thickness_m=sh["wall_thickness_m"],
        roof_material=sh["roof_material"], roof_thickness_m=sh["roof_thickness_m"],
        floor_material=sh["floor_material"], floor_thickness_m=sh["floor_thickness_m"],
        window=_win(sh["window"]), door=_door(sh["door"]),
        insulation_material=sh["insulation"]["material"],
        insulation_thickness_m=sh["insulation"]["thickness_m"],
    )

    lines = []
    add = lines.append
    add("! ============================================================================")
    add("! SIH26051 shelter shoebox model - GENERATED by simulation/energyplus/make_idf.py")
    add(f"! Location: {loc['name']} ({loc['latitude']}, {loc['longitude']})  year {year}")
    add("! ============================================================================")
    add(f"Version,{eplus.get('version', '26.1')};")
    add("")
    add("Building,")
    add("  SIH26051 Shelter Demo,           !- Name")
    add("  0.0,                             !- North Axis")
    add("  City,                            !- Terrain")
    add("  0.04,                            !- Loads Convergence Tolerance Value")
    add("  0.4,                             !- Temperature Convergence Tolerance Value")
    add("  FullExterior,                    !- Solar Distribution")
    add("  25,                              !- Maximum Number of Warmup Days")
    add("  6;                               !- Minimum Number of Warmup Days")
    add("")
    add(f"Timestep,{steps};")
    add("")
    add("GlobalGeometryRules,")
    add("  UpperLeftCorner,                 !- Starting Vertex Position")
    add("  CounterClockwise,                !- Vertex Entry Direction")
    add("  World;                           !- Coordinate System")
    add("")
    add("HeatBalanceAlgorithm,ConductionTransferFunction;")
    add("SurfaceConvectionAlgorithm:Inside,TARP;")
    add("SurfaceConvectionAlgorithm:Outside,DOE-2;")
    add("")
    add("SimulationControl,")
    add("  No,                              !- Do Zone Sizing")
    add("  No,                              !- Do System Sizing")
    add("  No,                              !- Do Plant Sizing")
    add("  Yes,                             !- Run Simulation for Sizing Periods")
    add("  Yes;                             !- Run Simulation for Weather File Run Periods")
    add("")
    add("Site:Location,")
    add(f"  {loc['name']},                     !- Name")
    add(f"  {loc['latitude']},                 !- Latitude {{deg}}")
    add(f"  {loc['longitude']},                !- Longitude {{deg}}")
    add("  5.5,                             !- Time Zone {{hr}} (GMT+5.5)")
    add(f"  {loc['elevation_m']};              !- Elevation {{m}}")
    add("")
    add("RunPeriod,")
    add("  Full Year,                       !- Name")
    add("  1, 1, ,                         !- Begin Month, Begin Day, Begin Year (blank = EPW year)")
    add("  12, 31, ,                       !- End Month, End Day, End Year")
    add("  ,                                !- Day of Week for Start Day")
    add("  ,                                !- Use Weather File Holidays/Special Days")
    add("  ,                                !- Use Weather File Daylight Saving")
    add("  No,                              !- Apply Weekend Holiday Rule")
    add("  Yes,                             !- Use Weather File Rain Indicators")
    add("  Yes;                             !- Use Weather File Snow Indicators")
    add("")

    # ---- materials & constructions ---------------------------------------
    used_materials = {}
    def mat_name(material, thick):
        key = (material, thick)
        if key not in used_materials:
            used_materials[key] = f"SIH{len(used_materials) + 1:02d}_{material}"
        return used_materials[key]

    for s in shelter.surfaces():
        if s["type"] == "window":
            continue
        for material, thick in s["layers"]:
            mat_name(material, thick)
    if shelter.window is not None:
        mat_name("glass", 0.0)

    for (material, thick), name in used_materials.items():
        if material == "glass":
            continue
        row = materials.loc[material]
        add("Material,")
        add(f"  {name},                        !- Name")
        add("  MediumRough,                   !- Roughness")
        add(f"  {thick:.4f},                   !- Thickness {{m}}")
        add(f"  {float(row['k_W_mK']):.4f},    !- Conductivity {{W/m-K}}")
        add(f"  {float(row['density_kg_m3']):.1f},  !- Density {{kg/m3}}")
        add(f"  {float(row['cp_J_kgK']):.1f},  !- Specific Heat {{J/kg-K}}")
        add(f"  {float(row['emissivity']):.2f},     !- Thermal Absorptance")
        add(f"  {float(row['solar_absorptance']):.2f},  !- Solar Absorptance")
        add(f"  {float(row['solar_absorptance']):.2f};  !- Visible Absorptance")
        add("")

    add("WindowMaterial:SimpleGlazingSystem,")
    add("  WinGlaz,                         !- Name")
    add(f"  {shelter.window.u_w_m2k},        !- U-Factor {{W/m2-K}}")
    add(f"  {shelter.window.shgc},           !- Solar Heat Gain Coefficient")
    add("  0.75;                            !- Visible Transmittance")
    add("")

    constructions = {}
    for s in shelter.surfaces():
        if s["type"] == "window":
            constructions["window"] = "WinCon"
            continue
        if s["type"] == "door":
            continue          # the door uses its base wall's construction
        layer_names = [mat_name(m, t) for (m, t) in s["layers"]]
        constructions[s["name"]] = f"Con_{s['name']}"
        add("Construction,")
        add(f"  {constructions[s['name']]},     !- Name")
        # NOTE: the last layer must carry the ';' terminator — a trailing
        # comma + standalone ';' creates an empty layer that breaks E+ 26.1
        for i, ln in enumerate(layer_names):
            term = ";" if i == len(layer_names) - 1 else ","
            add(f"  {ln}{term}                          !- Layer")
    add("Construction,WinCon,WinGlaz;")
    add("")

    # ---- zone --------------------------------------------------------------
    add("Zone,")
    add("  ShelterZone,                     !- Name")
    add("  0,                               !- Direction of Relative North")
    add("  0, 0, 0,                         !- X,Y,Z Origin")
    add("  1,                               !- Type (1 = simple zone)")
    add("  1,                               !- Multiplier")
    add(f"  {shelter.height_m:.2f},              !- Ceiling Height {{m}}")
    add(f"  {shelter.volume_m3:.2f},              !- Volume {{m3}}")
    add(f"  {shelter.length_m * shelter.width_m:.2f},  !- Floor Area {{m2}}")
    add("  ,                                !- Zone Inside Convection Algorithm")
    add("  ,                                !- Zone Outside Convection Algorithm")
    add("  ,                                !- Part of Total Floor Area")
    add("  ,                                !- Zone-Averaged Convection Algorithm")
    add("  ;                                !- Additional Properties")
    add("")

    # ---- surfaces -----------------------------------------------------------
    verts = _box_vertices(cfg)
    name_to_verts = {
        "south_wall": "south", "north_wall": "north", "east_wall": "east",
        "west_wall": "west", "roof": "roof", "floor": "floor",
    }
    for s in shelter.surfaces():
        if s["type"] == "window" or s["type"] == "door":
            continue
        stype = "Roof" if s["type"] == "roof" else ("Floor" if s["type"] == "floor" else "Wall")
        is_floor = s["type"] == "floor"
        add("BuildingSurface:Detailed,")
        add(f"  {s['name']},                    !- Name")
        add(f"  {stype},                        !- Surface Type")
        add(f"  {constructions[s['name']]},     !- Construction Name")
        add("  ShelterZone,                    !- Zone Name")
        add("  ,                               !- Space Name")
        add("  Outdoors,                       !- Outside Boundary Condition")
        add("  ,                               !- Outside Boundary Condition Object")
        add("  SunExposed,                     !- Sun Exposure")
        add("  WindExposed,                    !- Wind Exposure")
        add("  1.0,                            !- View Factor to Ground")
        add("  4,                              !- Number of Vertices")
        add(f"  {_fmt_verts(verts[name_to_verts[s['name']]])};")
        add("")

    # openings (attached to their base wall)
    base_by_name = {s["name"]: verts[name_to_verts[s["name"]]]
                    for s in shelter.surfaces() if s["name"] in name_to_verts}
    for s in shelter.surfaces():
        if s["type"] not in ("window", "door"):
            continue
        # which wall does it sit on? find via window spec wall name
        wall_name = None
        if s["type"] == "window":
            wall_name = shelter.window.wall
            z_sill = shelter.window.sill_height_m
            ow, oh = shelter.window.width_m, shelter.window.height_m
            otype = "Window"
            con = "WinCon"
        else:
            wall_name = shelter.door.wall
            z_sill = 0.0
            ow, oh = shelter.door.width_m, shelter.door.height_m
            otype = "Door"
            con = constructions[f"{wall_name}_wall"]
        wall_key = {"south": "south", "north": "north", "east": "east", "west": "west"}[wall_name]
        wall_len = {"south": sh["width_m"], "north": sh["width_m"],
                    "east": sh["length_m"], "west": sh["length_m"]}[wall_name]
        u0 = 0.5 - 0.5 * (ow / wall_len)
        u1 = 0.5 + 0.5 * (ow / wall_len)
        vo = _window_vertices(base_by_name[f"{wall_name}_wall"], u0, u1, z_sill, z_sill + oh)
        add("FenestrationSurface:Detailed,")
        add(f"  {s['name']},                    !- Name")
        add(f"  {otype},                        !- Surface Type")
        add(f"  {con},                          !- Construction Name")
        add(f"  {wall_name}_wall,               !- Building Surface Name")
        add("  ,                               !- Outside Boundary Condition Object")
        add("  0.5,                            !- View Factor to Ground")
        add("  ,                               !- Frame and Divider Name")
        add("  1,                              !- Multiplier")
        add("  4,                              !- Number of Vertices")
        add(f"  {_fmt_verts(vo)};")
        add("")

    # ---- outputs ------------------------------------------------------------
    add("Output:Variable,*,Site Outdoor Air Drybulb Temperature,hourly;")
    add("Output:Variable,*,Zone Mean Air Temperature,hourly;")
    add("Output:Variable,*,Zone Air Temperature,hourly;")
    add("Output:Variable,*,Surface Outside Face Incident Solar Radiation Rate per Area,hourly;")
    add("Output:Variable,*,Zone Windows Total Transmitted Solar Radiation Rate,hourly;")
    add("Output:Variable,*,Zone Ventilation Total Heat Loss Energy,hourly;")
    add("Output:SQLite,Simple;")
    add("Output:VariableDictionary,Regular;")

    text = "\n".join(lines) + "\n"
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"[idf] wrote {out_path} ({len(lines)} lines)")
    return out_path


def _win(w: dict):
    from src.geometry.shelter import WindowSpec
    return WindowSpec(wall=w["wall"], width_m=w["width_m"], height_m=w["height_m"],
                      sill_height_m=w.get("sill_height_m", 0.9),
                      u_w_m2k=w.get("u_w_m2k", 5.8), shgc=w.get("shgc", 0.82))


def _door(d: dict):
    from src.geometry.shelter import DoorSpec
    return DoorSpec(wall=d["wall"], width_m=d["width_m"], height_m=d.get("height_m", 1.95))
