"""AI design assistant — physics-informed surrogate of the sourced RC engine.

The model is a set of gradient-boosted regression trees trained OFFLINE
(scripts/ml/train_model.py) on a dataset generated by the validated RC
engine itself (scripts/ml/generate_dataset.py, real hourly weather for
12 Indian cities across all climate zones). Inference here is pure NumPy
(a compact JSON tree export, no scikit-learn at runtime) so the serverless
bundle stays small and the deployed physics never drifts.

Honesty contract (project rule: no invented numbers):
  * The AI only ever predicts metrics that were computed by the engine.
  * Accuracy (MAE / R2, incl. leave-one-site-out) is exported with the
    model and served by GET /api/ai/info — the UI always shows it.
  * The engine remains the source of truth: predictions are labelled
    estimates, and every suggestion can be engine-verified.
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path

import numpy as np
import pandas as pd

MODEL_FILE = Path(__file__).resolve().parent / "data" / "ai_model.json"

# --------------------------------------------------------------------------
# feature schema (ORDER MATTERS — must match the exported model)
# --------------------------------------------------------------------------
SITE_FEATURES = [
    "t_hottest_month_c", "t_coldest_month_c", "diurnal_range_c",
    "rh_mean_pct", "cdd18", "hdd18", "ghi_mean_w_m2", "wind_mean_ms",
    # v2: outdoor extremes + altitude. The targets are extremes, so a model
    # given only monthly means had to memorise each site to predict them and
    # could not transfer to an unseen one.
    "t_min_c", "t_max_c", "elevation_m",
]
DESIGN_FEATURES = [
    "length_m", "width_m", "height_m",
    "wall_r", "wall_mass_kg_m2", "wall_abs",
    "roof_r", "roof_mass_kg_m2", "roof_abs",
    "ins_r", "win_area_m2", "win_u_w_m2k", "win_shgc",
    "orient_sin", "orient_cos",
]
FEATURES = SITE_FEATURES + DESIGN_FEATURES

# Hot-week AND cold-week targets. v1 predicted only cold_min_c for winter,
# which says nothing about whether a cold-climate shelter is actually liveable
# — Leh, Dras, Kargil and Srinagar are designed against the cold week.
TARGETS = ["hot_mean_c", "hot_max_c", "hot_comfort_fraction",
           "cold_min_c", "cold_mean_c", "cold_comfort_fraction"]

#: Physics-informed residual targets (v2).
#:
#: Indoor extremes track the OUTDOOR extreme plus an envelope-dependent
#: offset. Fitting the absolute value made the trees span a 44.9 C range
#: across sites, and gradient-boosted trees cannot extrapolate: a site colder
#: than anything in training got clamped to the nearest leaf, which is why
#: leave-one-site-out MAE for cold_min_c was 11.5 C on Srinagar even though
#: the random holdout scored R2 = 1.0000.
#:
#: Fitting `indoor - outdoor` instead collapses that 44.9 C span to 2.5-13.4 C,
#: and an unseen site's offset lands INSIDE the range other sites already
#: cover — interpolation rather than extrapolation. The baseline is a feature
#: the model already receives, so inference just adds it back.
RESIDUAL_BASE = {
    "cold_min_c": "t_min_c",
    "cold_mean_c": "t_min_c",
    "hot_max_c": "t_max_c",
    "hot_mean_c": "t_max_c",
}

# --------------------------------------------------------------------------
# design space used for dataset generation AND for the AI suggestion search
# (discrete, deterministic — every value maps 1:1 onto the flat design schema
# the engine consumes, so suggestions are always simulatable)
# --------------------------------------------------------------------------
WALL_CHOICES = {
    "brick": [0.115, 0.23, 0.345],
    "rammed_earth": [0.15, 0.3, 0.45],
    "concrete": [0.1, 0.15, 0.2, 0.3],
    "gi_sheet": [0.002],
    "plywood": [0.012, 0.019, 0.03, 0.05],
    "puf_sandwich_panel": [0.05, 0.075, 0.1, 0.15],
    "stone": [0.15, 0.3, 0.45],          # high-altitude masonry (Ladakh)
    "mud_brick": [0.15, 0.3, 0.45],      # vernacular adobe
    "timber": [0.1, 0.15, 0.2],          # lightweight frame
    "aerated_concrete": [0.1, 0.2, 0.3], # AAC block
}
ROOF_CHOICES = {
    "rcc_slab": [0.1, 0.15, 0.2, 0.25],
    "concrete": [0.1, 0.15, 0.2],
    "gi_sheet": [0.002],
    "puf_sandwich_panel": [0.05, 0.075, 0.1, 0.15],
    "brick": [0.115, 0.23],
    "stone": [0.15, 0.3],               # heavy cold-climate slab
    "mud_brick": [0.15, 0.25],          # flat mud roof (Ladakh tradition)
    "timber": [0.1, 0.15],              # pitched/beam deck
    "aerated_concrete": [0.1, 0.2],
}
INSULATION_CHOICES = [
    ("none", 0.0),
    ("eps", 0.025), ("eps", 0.05), ("eps", 0.1), ("eps", 0.15), ("eps", 0.2),
    ("xps", 0.05), ("xps", 0.1), ("xps", 0.15),
    ("mineral_wool", 0.05), ("mineral_wool", 0.1), ("mineral_wool", 0.15),
    ("sheep_wool", 0.05), ("sheep_wool", 0.1), ("sheep_wool", 0.15),
]
WINDOW_WALLS = ["north", "east", "south", "west"]
WINDOW_WIDTHS = [0.6, 0.9, 1.2, 1.5, 1.8]
WINDOW_HEIGHTS = [0.6, 0.9, 1.2, 1.5]
WINDOW_SHGC = [0.35, 0.45, 0.55, 0.65, 0.75, 0.85]
# triple low-e (1.2), low-e double (1.6), clear double (2.0/2.6),
# single clear (3.5/5.8) — ASHRAE HOF 2021 Ch.15 typical assembled U-values
WINDOW_U = [1.2, 1.6, 2.0, 2.6, 3.5, 5.8]
ORIENTATIONS = [0, 45, 90, 135, 180]
LENGTHS = [3.0]
WIDTHS = [3.0]
HEIGHTS = [2.6]


def sample_design(rng: np.random.Generator) -> dict:
    """Draw one random flat-schema design from the training space."""
    wall_mat = rng.choice(list(WALL_CHOICES))
    roof_mat = rng.choice(list(ROOF_CHOICES))
    ins_mat, ins_thk = INSULATION_CHOICES[int(rng.integers(len(INSULATION_CHOICES)))]
    return {
        "length_m": float(rng.choice(LENGTHS)),
        "width_m": float(rng.choice(WIDTHS)),
        "height_m": float(rng.choice(HEIGHTS)),
        "orientation_deg": float(rng.choice(ORIENTATIONS)),
        "wall_material": str(wall_mat),
        "wall_thickness_m": float(rng.choice(WALL_CHOICES[wall_mat])),
        "roof_material": str(roof_mat),
        "roof_thickness_m": float(rng.choice(ROOF_CHOICES[roof_mat])),
        "floor_material": "concrete",
        "floor_thickness_m": 0.1,
        "insulation_material": str(ins_mat),
        "insulation_thickness_m": float(ins_thk),
        "window_wall": str(rng.choice(WINDOW_WALLS)),
        "window_width_m": float(rng.choice(WINDOW_WIDTHS)),
        "window_height_m": float(rng.choice(WINDOW_HEIGHTS)),
        "window_sill_m": 0.9,
        "window_shgc": float(rng.choice(WINDOW_SHGC)),
        "window_u_w_m2k": float(rng.choice(WINDOW_U)),
    }


# --------------------------------------------------------------------------
# physics-informed features (computed from SOURCED properties, same helpers
# the RC engine itself uses — guarantees training == runtime encoding)
# --------------------------------------------------------------------------
def build_features(design: dict, profile: dict, mats: pd.DataFrame) -> list[float]:
    from src.thermal.rc_model import surface_conductance, surface_mass

    def r_of(mat, thk):
        if mat not in mats.index:
            return 0.0
        return 1.0 / surface_conductance([(mat, thk)], mats)

    def mass_of(mat, thk):
        if mat not in mats.index:
            return 0.0
        return surface_mass([(mat, thk)], mats)

    wall_mat = design.get("wall_material", "brick")
    wall_thk = float(design.get("wall_thickness_m", 0.2))
    roof_mat = design.get("roof_material", "rcc_slab")
    roof_thk = float(design.get("roof_thickness_m", 0.12))
    ins_mat = design.get("insulation_material", "none")
    ins_thk = float(design.get("insulation_thickness_m", 0.0))
    win_w = float(design.get("window_width_m", 1.2))
    win_h = float(design.get("window_height_m", 1.2))
    orient = float(design.get("orientation_deg", 0.0))
    rad = math.radians(orient)

    ins_r = (ins_thk / float(mats.loc[ins_mat, "k_W_mK"])) if (
        ins_mat != "none" and ins_mat in mats.index and ins_thk > 0) else 0.0

    def abs_of(mat):
        return float(mats.loc[mat, "solar_absorptance"]) if mat in mats.index else 0.7

    f = [
        float(profile["t_hottest_month_c"]),
        float(profile["t_coldest_month_c"]),
        float(profile["diurnal_range_c"]),
        float(profile["rh_mean_pct"]),
        float(profile["cdd18"]),
        float(profile["hdd18"]),
        float(profile["ghi_mean_w_m2"]),
        float(profile["wind_mean_ms"]),
        # fall back to the monthly means when an older profile lacks the v2
        # keys, so stale cached profiles degrade instead of crashing
        float(profile.get("t_min_c") if profile.get("t_min_c") is not None
              else profile["t_coldest_month_c"]),
        float(profile.get("t_max_c") if profile.get("t_max_c") is not None
              else profile["t_hottest_month_c"]),
        float(profile.get("elevation_m") or 0.0),
        float(design.get("length_m", 3.0)),
        float(design.get("width_m", 3.0)),
        float(design.get("height_m", 2.6)),
        r_of(wall_mat, wall_thk),
        mass_of(wall_mat, wall_thk),
        abs_of(wall_mat),
        r_of(roof_mat, roof_thk),
        mass_of(roof_mat, roof_thk),
        abs_of(roof_mat),
        ins_r,
        win_w * win_h,
        float(design.get("window_u_w_m2k", 5.8)),
        float(design.get("window_shgc", 0.82)),
        math.sin(rad),
        math.cos(rad),
    ]
    assert len(f) == len(FEATURES), (len(f), len(FEATURES))
    return f


# --------------------------------------------------------------------------
# model load + pure-NumPy batch inference
# --------------------------------------------------------------------------
_MODEL = None


def load_model(model: dict | None = None) -> dict:
    global _MODEL
    if model is not None:
        _MODEL = model
    if _MODEL is None:
        with open(MODEL_FILE, "r", encoding="utf-8") as fh:
            _MODEL = json.load(fh)
    return _MODEL


def _walk_tree(tree: dict, X: np.ndarray, idx: np.ndarray) -> np.ndarray:
    """Batch tree walk over exported sklearn nodes.

    `tree` = {"left":[...], "right":[...], "feature":[...],
    "threshold":[...], "value":[...], "is_leaf":[...]} — explicit child
    indices per node, leaves flagged by is_leaf (HistGradientBoosting
    layout). Falls back to `left < 0` when is_leaf is absent (classic
    GradientBoosting layout). Returns per-sample leaf value."""
    n = len(X)
    cur = np.zeros(n, dtype=np.int64)          # current node per sample
    val = np.zeros(n, dtype=np.float64)
    left = np.asarray(tree["left"], dtype=np.int64)
    right = np.asarray(tree["right"], dtype=np.int64)
    feat = np.asarray(tree["feature"], dtype=np.int64)
    thr = np.asarray(tree["threshold"], dtype=np.float64)
    leaf_v = np.asarray(tree["value"], dtype=np.float64)
    is_leaf = tree.get("is_leaf")
    if is_leaf is not None:
        is_leaf = np.asarray(is_leaf, dtype=bool)
        is_leaf_fn = lambda node: is_leaf[node]
    else:
        is_leaf_fn = lambda node: left[node] < 0
    active = np.ones(n, dtype=bool)
    while active.any():
        node = cur[active]
        leaf_mask = is_leaf_fn(node)
        # resolve leaves first
        leaf_idx = node[leaf_mask]
        samp_idx = np.nonzero(active)[0][leaf_mask]
        val[samp_idx] = leaf_v[leaf_idx]
        # advance non-leaves
        go = active.copy()
        go[active] = ~leaf_mask
        if not go.any():
            break
        node2 = cur[go]
        feats = X[np.nonzero(go)[0], feat[node2]]
        to_left = feats <= thr[node2]
        cur[go] = np.where(to_left, left[node2], right[node2])
        active[go] = cur[go] >= 0
    return val


def predict_batch(X: np.ndarray, model: dict | None = None) -> dict[str, np.ndarray]:
    """Predict all targets for a (n_samples x n_features) float array.

    `model` may be passed explicitly (the trainer uses this to validate
    an in-memory export BEFORE it is written to disk); defaults to the
    on-disk model.
    """
    model = load_model(model)
    bases = model.get("residual_base", {})
    out = {}
    for target, spec in model["targets"].items():
        init = float(spec.get("init", 0.0))
        pred = np.full(len(X), init, dtype=np.float64)
        for tree in spec["trees"]:
            # sklearn >= 1.6 shrinks leaf values by learning_rate at fit
            # time, so inference must NOT multiply again.
            pred += _walk_tree(tree, X, None)
        # residual targets are learned as (indoor - outdoor); restore the
        # absolute value using the same feature the trainer subtracted
        base_feat = bases.get(target)
        if base_feat:
            pred = pred + X[:, model["features"].index(base_feat)]
        out[target] = pred
    return out


def predict_design(design: dict, profile: dict, mats: pd.DataFrame) -> dict:
    """Instant estimates for one design at one site (rounded for display)."""
    X = np.asarray([build_features(design, profile, mats)], dtype=np.float64)
    p = predict_batch(X)
    est = {
        "hot_mean_c": round(float(p["hot_mean_c"][0]), 1),
        "hot_max_c": round(float(p["hot_max_c"][0]), 1),
        "hot_comfort_fraction": round(float(np.clip(p["hot_comfort_fraction"][0], 0.0, 1.0)), 3),
        "cold_min_c": round(float(p["cold_min_c"][0]), 1),
    }
    m = model_metrics()
    return {
        "estimates": est,
        "error_bars_c": {t: m["targets"][t]["mae_c"] for t in ("hot_mean_c", "hot_max_c", "cold_min_c")},
        "model": model_meta(),
    }


def model_metrics() -> dict:
    return load_model().get("metrics", {})


def model_meta() -> dict:
    m = load_model()
    meta = m.get("metadata", {})
    return {
        "name": meta.get("name", "rc-surrogate"),
        "n_samples": meta.get("n_samples", 0),
        "n_sites": meta.get("n_sites", 0),
        "sites": meta.get("sites", []),
        "n_trees": meta.get("n_trees", 0),
        "trained_on": meta.get("trained_on", ""),
    }
